// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcjq8AgpKOxxL4OEW2KDivJK5eaxnAOQ',
    appId: '1:867295840104:web:7756187231864b2e53b8dd',
    messagingSenderId: '867295840104',
    projectId: 'kliniku-67c42',
    authDomain: 'kliniku-67c42.firebaseapp.com',
    storageBucket: 'kliniku-67c42.appspot.com',
    measurementId: 'G-J2J9NJTBX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyVf_CL_ESQdrT1yTU1YhxUP76Gz48k8',
    appId: '1:867295840104:android:f3412160cadb044c53b8dd',
    messagingSenderId: '867295840104',
    projectId: 'kliniku-67c42',
    storageBucket: 'kliniku-67c42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKjCariq1j8ALsk69wKWxBKB7Wui5gHYo',
    appId: '1:867295840104:ios:8fa5a09da5fa0d5653b8dd',
    messagingSenderId: '867295840104',
    projectId: 'kliniku-67c42',
    storageBucket: 'kliniku-67c42.appspot.com',
    iosClientId: '867295840104-n17osokkul6l6c8p57jrqqibqn8lla0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.kliniku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKjCariq1j8ALsk69wKWxBKB7Wui5gHYo',
    appId: '1:867295840104:ios:8fa5a09da5fa0d5653b8dd',
    messagingSenderId: '867295840104',
    projectId: 'kliniku-67c42',
    storageBucket: 'kliniku-67c42.appspot.com',
    iosClientId: '867295840104-n17osokkul6l6c8p57jrqqibqn8lla0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.kliniku',
  );
}
